apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  labels:
    project: expense
    component: mysql
    Environment: development
spec:
  serviceName: mysql
  replicas: 3
  selector:
    matchLabels:
      project: expense
      component: mysql
      Environment: development
  template:
    metadata:
      labels:
        project: expense
        component: mysql
        Environment: development
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
      containers:
      - name: mysql
        image: kalyaneswarm/mysql:v1.0
        ports:
        - containerPort: 3306
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
        livenessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 10
          periodSeconds: 5
  volumeClaimTemplates:
  - metadata:
      name: mysql-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "expense-ebs"
      resources:
        requests:
          storage: 1Gi
