
---
# MySQL Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    project: expense
    component: mysql
    Environment: development
spec:
  replicas: 3
  selector:
    matchLabels:
      project: expense
      component: mysql
      Environment: development
  template:
    metadata:
      labels:
        project: expense
        component: mysql
        Environment: development
    spec:
      containers:
      - name: mysql
        image: kalyaneswarm/mysql:v1.0
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
        livenessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 10
          periodSeconds: 5
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-pvc
---

