apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    project: expense
    component: mysql
    Environment: development
spec:
  replicas: 3
  selector:
    matchLabels:
      project: expense
      component: mysql
      Environment: development
  template:
    metadata:
      labels:
        project: expense
        component: mysql
        Environment: development
    spec:
      containers:
      - name: mysql
        image: kalyaneswarm/mysql:v1.0
        ports:
        - containerPort: 3306
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
